databases:
  - name: hotwire_forums_db
    databaseName: hotwire_forums_production
    user: hotwire_forums
    plan: free

services:
  - type: web
    name: hotwire_forums
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hotwire_forums_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          name: hotwire_forums_redis
          property: connectionString
  - type: redis
    name: hotwire_forums_redis
    plan: free
