databases:
  - name: hotwire_forums_db
    databaseName: hotwire_forums_production
    user: hotwire_forums
    plan: free
    ipAllowList: []

services:
  - type: web
    name: hotwire_forums
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hotwire_forums_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: hotwire_forums_redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: APPSIGNAL_PUSH_API_KEY
        sync: false
  - type: redis
    name: hotwire_forums_redis
    plan: free
    ipAllowList: []
