databases:
  - name: hotwire_forums
    databaseName: hotwire_forums_production
    user: hotwire_forums

services:
  - type: web
    name: hotwire_forums
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hotwire_forums
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
